trigger:
  - master

pool:
  vmImage: "ubuntu-latest"

variables:
  buildConfiguration: "Release"
steps:
  - task: GitVersion@5
  - script: |
      echo '##vso[task.setvariable variable=buildVersion]$(GitVersion.FullSemVer")'
  - script: |
      echo //registry.npmjs.org/:_authToken=$(NPM_TOKEN) > .npmrc
    displayName: 'npm Authentication'
  - task: Docker@2
    inputs:
      containerRegistry: acrHiab
      repository: "hiab-components"
      command: "buildAndPush"
      Dockerfile: "**/Dockerfile"

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: "$(Build.SourcesDirectory)/deploy/hiab-components"
      ArtifactName: "charts"
      publishLocation: "Container"
